--- 
title: "Reproducible Analytical Science using R and Python"
author: "John Minter"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Microscopy and micronalysis in R and Python. The output format for this example is bookdown::gitbook."
---

# Prologue

I spent a 36 year career in the Analytical Sciences Division of a large
corporation. My main areas of focus were electron microscopy, image
analysis, and electron microanalysis using X-ray energy-dispersive
spectroscopy (EDS). I quickly learned that embracing automation and
scripted analysis gave me more time to think about the meaning of the
results I obtained and eliminated error-prone repetitive data processing.

By the end of my career, I had embraced Donald Knuth's idea of
**Literate Programming**, where the code to run the data analysis is
embedded as **code chunks** in the report, automatically generating
the results. Like many scientists who work in analytical laboratories,
I found myself repeatedly writing the same code. By that time I had
embraced both **python** and **R**, and had learned the benefit of
collecting code into functions and packages maintained under version
control and tested with unit tests.

> If you write the same code more than twice, incorporate it into a
> function and keep it in a package under version control.

I also discovered that the **python** and **R-stats** communities were
welcoming and had already solved many of the problems I needed to solve.
There were packages that did much of what I needed to do and I could
make my non-proprietary code available as a way of giving something back.
My management supported these activities because most of the tools that
I used were Open Source and we were always under severe budgetary 
constraints.

My new workflow was both more enjoyable and more intellectually
stimulating. As our headcount went down, I found like-minded individuals
in the larger community helped me to continue to learn and grow. This
benefitted all of our employers without revealing proprietary
information.

In this book I will show how to use these tools to make a more robust
and reproducible data analysis.
